### ISSUE TITLE
Memory-related bug

### ISSUE THREAD

**Issue by Clemcarle** [swom/ArchitectureEvolution#243] opened 2022-01-21 14:25 UTC
@HHildenbrandt , hoping you could help with this. Here is a description of the problem. I've included as much detail as possible, but do ask me anything else you need. 

When I am running the program from the `duplications` branch, with the following set of parameters: 
`-C 0.005 -X 1,8,8,8,1 -N 1,2,2,2,1 -G 200000 -m NRduplication`, 
the code runs normally for a bit over 28 000 generations, then crashes, giving me the following error message: "exited with code -1073741510". 
This seems to correspond to an access violation. 

We think this is related to a memory "leak" issue because: 

- This error does not occur (within 50000 generations) on Stefano's work computer, which is more powerful and has more memory than my laptop.
- This error does not occur for one run after I delete the folder the program gets built in (which is also where the results get saved) and re-build.
- This error does not occur (within 50000 generations) if I delete, in our `exec()` function in `observer.h`, the parts of the code related to storing information into the observer. 

I use Qt creator 4.15.0 with Qt 6.1.0 on a Windows 10 computer. 
Here is a screenshot from the building configuration in case that is relevant. 
![image](https://user-images.githubusercontent.com/83981278/150543312-683c97fd-9263-427a-82d9-ecb8e7f93e3d.png)

**Comment by HHildenbrandt** [comment] 2022-01-26 13:10
Can't find anything - memory leak is very unlikely because of the overall memory use is low.

error code -1073741510 (0xc000013a) relates to a program closed by "CTRL-C" or closing the command-window. Your sim is terminated from outside...

I guess you didn't trigger CTRL-C by ourself ;)
Quite strange. Since you are using a laptop try to disable sleep and power-saving. If you run the sim from an network-drive (things like UWP, google-drive, oneDrive, dropbox, ...) try to run it from a physical drive.

Cheers,
Hanno

**Comment by Clemcarle** [comment] 2022-01-27 09:52
@HHildenbrandt I realized now I copy-pasted the wrong error code - this one must have been left on the console from one simulation where I did close the console manually. The actual error code is  `-1073741819`. I am sorry about the incorrect information. 
I am pretty sure this is not coming strictly from my PC; I have checked battery saving, sleep mode, etc. I am running from a physical drive. Changing basically anything in the code (even switching around lines whose order shouldn't really matter) changes the point at which the crash occurs, but i've not been able to find a version of the code where it doesn't crash within 200 000 generations. 
I've been running it while checking its memory usage, indeed it does not seem to be the case that too much of the memory is used right before it crashes. 
I am at a loss. Thank you if you have any ideas.

**Comment by HHildenbrandt** [comment] 2022-02-01 10:22
Hi,  -1073741819 is 0xc0000005 in hex -- the dreadful 'access violation'
error.
I couldn't reproduce the issue on my computer(s) yet. Can you give me some
more information about your computer? Things like RAM, CPU, Windows
Version, Disks size, Compiler version and so on. Hm, Maybe it is best to
have a online-chat late this afternoon?

Cheers,
Hanno

**Comment by Clemcarle** [comment] 2022-02-01 10:34
Hi Hanno, thanks for looking into it! 
The error happens on my computer, as well as Stefano's (I think) and on the cluster, but sometimes it takes a very long time, like 100 000 + generations. 
Here is my computer's info: 
8 Go Ram 
CPU : 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Windows 10 Family version 21H1
475 Go total disk size - 346 Go free

**Comment by Clemcarle** [comment] 2022-02-03 13:58
@HHildenbrandt Just tagging you to make sure that you've seen this (I'm not sure how github notifications work), and yes let me know if you it would be helpful to meet, and when, to discuss this bug further.

**Closed** 2022-02-16 13:31 UTC
Labels: bug
